/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */
import { BuildingConfig, BuildingType, GameSettings } from "./types";

// Map Settings
export const GRID_SIZE = 15;
export const MAX_GRID_SIZE = 30;
export const MIN_GRID_SIZE = 5;

// Game Settings
export const TICK_RATE_MS = 2000; // Game loop updates every 2 seconds
export const INITIAL_MONEY = 1000;

export const INITIAL_SETTINGS: GameSettings = {
  display: "minimal",
  uiScale: 1,
  fpsLimit: 30,
  volume: 0.7,
  weather: "sunny",
  weatherIntensity: 0.5,
  weatherFrequency: 0.3,
  graphicsQuality: "low",
  gameSpeed: 1,
  timeScale: 1,
  panLocked: false,
  camLocked: false,
  autoScrollNews: true,
  showTooltips: true,
  showLevelIndicators: true,
  soundEnabled: true,
  ambientEnabled: true,
  volumetricFog: false,
  fogDensity: 0.5,
  lodEnabled: true,
  textureLevel: 0,
  shadowQuality: "low",
  shadowDarkness: 0.5,
  antiAliasing: false,
  reflections: false,
  secondaryColor: "#facc15",
  theme: "cyber",
  npcAppearance: {
    advisorColor: "#3b82f6",
    citizenColor: "#ec4899",
    skinColor: "#fcd34d",
  },
  cameraZoomSensitivity: 1,
  maxVehicles: 20,
  orientation: 'auto',
  cameraPerspective: 'isometric',
  brightness: 1,
  contrast: 1,
  bloomIntensity: 1,
  globalLight: 1,
  nightLight: 1,
  nightDarkness: 1,
};

export const BUILDINGS: Record<BuildingType, BuildingConfig> = {
  [BuildingType.None]: {
    type: BuildingType.None,
    cost: 0,
    name: "Bulldoze",
    description: "Clear a tile",
    color: "#ef4444",
    popGen: 0,
    incomeGen: 0,
  },
  [BuildingType.Road]: {
    type: BuildingType.Road,
    cost: 10,
    name: "Road",
    description: "Basic road for transit.",
    color: "#374151",
    popGen: 0,
    incomeGen: 0,
    upgradeCost: 50,
    maxLevel: 3,
  },
  [BuildingType.Residential]: {
    type: BuildingType.Residential,
    cost: 100,
    name: "House",
    description: "Homes for citizens.",
    color: "#f87171",
    popGen: 5,
    incomeGen: 0,
    upgradeCost: 150,
    maxLevel: 5,
  },
  [BuildingType.Commercial]: {
    type: BuildingType.Commercial,
    cost: 200,
    name: "Shop",
    description: "Basic commerce.",
    color: "#60a5fa",
    popGen: 0,
    incomeGen: 15,
    upgradeCost: 200,
    maxLevel: 5,
  },
  [BuildingType.Industrial]: {
    type: BuildingType.Industrial,
    cost: 400,
    name: "Factory",
    description: "Heavy production.",
    color: "#fbbf24",
    popGen: 0,
    incomeGen: 40,
    upgradeCost: 500,
    maxLevel: 4,
  },
  [BuildingType.Park]: {
    type: BuildingType.Park,
    cost: 50,
    name: "Park",
    description: "Leisure space.",
    color: "#4ade80",
    popGen: 1,
    incomeGen: 2,
    upgradeCost: 100,
    maxLevel: 3,
  },
  [BuildingType.Mansion]: {
    type: BuildingType.Mansion,
    cost: 1500,
    name: "Mansion",
    description: "Luxury housing.",
    color: "#d946ef",
    popGen: 10,
    incomeGen: 50,
    upgradeCost: 1000,
    maxLevel: 3,
  },
  [BuildingType.Hotel]: {
    type: BuildingType.Hotel,
    cost: 2500,
    name: "Hotel",
    description: "Tourism & lodging.",
    color: "#06b6d4",
    popGen: 0,
    incomeGen: 200,
    upgradeCost: 1500,
    maxLevel: 4,
  },
  [BuildingType.Casino]: {
    type: BuildingType.Casino,
    cost: 10000,
    name: "Casino",
    description: "High risk high reward.",
    color: "#f43f5e",
    popGen: 0,
    incomeGen: 1000,
    upgradeCost: 5000,
    maxLevel: 3,
  },
  [BuildingType.Library]: {
    type: BuildingType.Library,
    cost: 800,
    name: "Library",
    description: "Knoewledge hub.",
    color: "#8b5cf6",
    popGen: 2,
    incomeGen: 5,
  },
  [BuildingType.Restaurant]: {
    type: BuildingType.Restaurant,
    cost: 600,
    name: "Restaurant",
    description: "Fine dining.",
    color: "#f97316",
    popGen: 0,
    incomeGen: 80,
  },
  [BuildingType.FastFood]: {
    type: BuildingType.FastFood,
    cost: 400,
    name: "Fast Food",
    description: "Quick bites.",
    color: "#eab308",
    popGen: 0,
    incomeGen: 120,
  },
  [BuildingType.GasStation]: {
    type: BuildingType.GasStation,
    cost: 500,
    name: "Gas Station",
    description: "Auto services.",
    color: "#6366f1",
    popGen: 0,
    incomeGen: 70,
  },
  [BuildingType.Bridge]: {
    type: BuildingType.Bridge,
    cost: 500,
    name: "Bridge",
    description: "Span over water.",
    color: "#94a3b8",
    popGen: 0,
    incomeGen: 0,
  },
  [BuildingType.Tunnel]: {
    type: BuildingType.Tunnel,
    cost: 1000,
    name: "Tunnel",
    description: "Underground transit.",
    color: "#1e293b",
    popGen: 0,
    incomeGen: 0,
  },
  [BuildingType.Wall]: {
    type: BuildingType.Wall,
    cost: 20,
    name: "Wall",
    description: "Perimeter defense.",
    color: "#475569",
    popGen: 0,
    incomeGen: 0,
  },
  [BuildingType.ApartmentComplex]: {
    type: BuildingType.ApartmentComplex,
    cost: 1500,
    name: "Apartment Complex",
    description: "High density living.",
    color: "#fb923c",
    popGen: 50,
    incomeGen: 20,
    upgradeCost: 2000,
    maxLevel: 4,
    powerRequired: 10,
    waterRequired: 10,
  },
  [BuildingType.Skyscraper]: {
    type: BuildingType.Skyscraper,
    cost: 50000,
    name: "Skyscraper",
    description: "Towering business hub.",
    color: "#38bdf8",
    popGen: 100,
    incomeGen: 2500,
    upgradeCost: 25000,
    maxLevel: 5,
    powerRequired: 50,
    waterRequired: 50,
    happinessGen: -5,
  },
  [BuildingType.University]: {
    type: BuildingType.University,
    cost: 12000,
    name: "University",
    description: "Advanced education.",
    color: "#c084fc",
    popGen: 10,
    incomeGen: 100,
    powerRequired: 20,
    waterRequired: 10,
    happinessGen: 20,
  },
  [BuildingType.PowerPlant]: {
    type: BuildingType.PowerPlant,
    cost: 5000,
    name: "Power Plant",
    description: "Generates power for the city.",
    color: "#fcd34d",
    popGen: 0,
    incomeGen: -50,
    powerGen: 100,
    waterRequired: 5,
    happinessGen: -10,
  },
  [BuildingType.WaterTower]: {
    type: BuildingType.WaterTower,
    cost: 2000,
    name: "Water Tower",
    description: "Supplies water to the city.",
    color: "#60a5fa",
    popGen: 0,
    incomeGen: -20,
    waterGen: 100,
    powerRequired: 5,
    happinessGen: 0,
  },
};
